update

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -19,6 +19,14 @@ else
   echo "prettier checks passed"
 fi
 
+# Run terraform format checks
+if ! just -q tofu-fmt-check; then
+  echo "Warning: tofu-fmt-check command failed"
+  exit 1
+else
+  echo "tofu-fmt-check checks passed"
+fi
+
 # Run just format checks
 if ! just -q format-check; then
   echo "Warning: format-check command failed"
